name: "pactflow"

on:
  push:
    branches-ignore:
      - "master"

  pull_request:
    types:
      - "closed"

env:
  application_name: "pact-demo-client1"
  PACT_BROKER_BASE_URL: ${{ secrets.PACT_BROKER_BASE_URL }}
  PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}

jobs:
  test-release:
    runs-on: ubuntu-latest
    container:
      image: pactfoundation/pact-cli:latest
      env:
        application_name: "pact-demo-client1"
        PACT_BROKER_BASE_URL: ${{ secrets.PACT_BROKER_BASE_URL }}
        PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
      volumes:
        - ${PWD}:${PWD}

      options: --rm
    steps:
      - uses: actions/checkout@v2
      - run: ./.github/workflows/setVersion.sh

      - run: publish src/pact/pactfiles --consumer-app-version 1.0.0 tag-with-git-branch

      #   - uses: pactflow/actions/publish-pact-files@v1.0.1
      #     env:
      #       pactfiles: ./src/pact/pactfiles
      #   - uses: pactflow/actions/can-i-deploy@v1.0.1
      #     env:
      #       to: prod

  tag-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./.github/workflows/setVersion.sh
      - uses: pactflow/actions/create-version-tag@v1.0.1
        env:
          tag: prod
